/**
 * Hook that returns helpers to call on-chain escrow instructions.
 * The program IDL is loaded from lib/escrow_freelancer_offers.json.
 * Run `npm run copy-idl` (from /app) after each `anchor build` to refresh it.
 */

import { useMemo } from "react";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import { Program, AnchorProvider, setProvider, Idl, BN } from "@coral-xyz/anchor";
import { PublicKey, SystemProgram, LAMPORTS_PER_SOL } from "@solana/web3.js";

// Import IDL — generated by `anchor build`, copied with `npm run copy-idl`
// If this file is missing: run `anchor build` then `npm run copy-idl` from /app
import idl from "./escrow_freelancer_offers.json";

const PROGRAM_ID = new PublicKey(
  process.env.NEXT_PUBLIC_PROGRAM_ID ??
    "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
);

// ─── PDA derivation helpers ──────────────────────────────────────────────────

export function deriveJobOfferPda(
  clientPubkey: PublicKey,
  jobId: bigint
): PublicKey {
  const idBuffer = Buffer.alloc(8);
  // Write jobId as little-endian u64
  const low = Number(jobId & BigInt(0xffffffff));
  const high = Number((jobId >> BigInt(32)) & BigInt(0xffffffff));
  idBuffer.writeUInt32LE(low, 0);
  idBuffer.writeUInt32LE(high, 4);

  const [pda] = PublicKey.findProgramAddressSync(
    [Buffer.from("job_offer"), clientPubkey.toBuffer(), idBuffer],
    PROGRAM_ID
  );
  return pda;
}

export function deriveProposalPda(
  jobOfferPda: PublicKey,
  freelancerPubkey: PublicKey
): PublicKey {
  const [pda] = PublicKey.findProgramAddressSync(
    [Buffer.from("proposal"), jobOfferPda.toBuffer(), freelancerPubkey.toBuffer()],
    PROGRAM_ID
  );
  return pda;
}

export function deriveVaultPda(jobOfferPda: PublicKey): PublicKey {
  const [pda] = PublicKey.findProgramAddressSync(
    [Buffer.from("vault"), jobOfferPda.toBuffer()],
    PROGRAM_ID
  );
  return pda;
}

// ─── Hook ────────────────────────────────────────────────────────────────────

export function useEscrowProgram() {
  const { connection } = useConnection();
  const wallet = useWallet();

  const program = useMemo(() => {
    if (!wallet.publicKey || !wallet.signTransaction) return null;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const provider = new AnchorProvider(connection, wallet as any, {
      commitment: "confirmed",
    });
    setProvider(provider);

    return new Program(idl as Idl, provider);
  }, [connection, wallet]);

  // ── create_offer ──────────────────────────────────────────────────────────
  async function createOffer(params: {
    jobId: bigint;
    title: string;
    description: string;
    amountSol: number; // in SOL (will be converted to lamports)
  }): Promise<string> {
    if (!program || !wallet.publicKey) throw new Error("Wallet not connected");

    const jobOfferPda = deriveJobOfferPda(wallet.publicKey, params.jobId);
    const amountLamports = Math.floor(params.amountSol * LAMPORTS_PER_SOL);

    // BN from bigint
    const jobIdBN = new BN(params.jobId.toString());
    const amountBN = new BN(amountLamports);

    const tx = await program.methods
      .createOffer(jobIdBN, params.title, params.description, amountBN)
      .accounts({
        jobOffer: jobOfferPda,
        client: wallet.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    return tx;
  }

  // ── offer_proposal ────────────────────────────────────────────────────────
  async function offerProposal(params: {
    jobOfferPda: string;
    message: string;
  }): Promise<string> {
    if (!program || !wallet.publicKey) throw new Error("Wallet not connected");

    const jobOfferKey = new PublicKey(params.jobOfferPda);
    const proposalPda = deriveProposalPda(jobOfferKey, wallet.publicKey);

    const tx = await program.methods
      .offerProposal(params.message)
      .accounts({
        jobOffer: jobOfferKey,
        proposal: proposalPda,
        freelancer: wallet.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    return tx;
  }

  // ── accept_proposal ───────────────────────────────────────────────────────
  async function acceptProposal(params: {
    jobOfferPda: string;
    freelancerPubkey: string;
  }): Promise<string> {
    if (!program || !wallet.publicKey) throw new Error("Wallet not connected");

    const jobOfferKey = new PublicKey(params.jobOfferPda);
    const freelancerKey = new PublicKey(params.freelancerPubkey);
    const proposalPda = deriveProposalPda(jobOfferKey, freelancerKey);
    const vaultPda = deriveVaultPda(jobOfferKey);

    const tx = await program.methods
      .acceptProposal()
      .accounts({
        jobOffer: jobOfferKey,
        proposal: proposalPda,
        client: wallet.publicKey,
        vault: vaultPda,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    return tx;
  }

  // ── complete_proposal ─────────────────────────────────────────────────────
  async function completeProposal(params: {
    jobOfferPda: string;
    freelancerPubkey: string;
  }): Promise<string> {
    if (!program || !wallet.publicKey) throw new Error("Wallet not connected");

    const jobOfferKey = new PublicKey(params.jobOfferPda);
    const freelancerKey = new PublicKey(params.freelancerPubkey);
    const vaultPda = deriveVaultPda(jobOfferKey);

    const tx = await program.methods
      .completeProposal()
      .accounts({
        jobOffer: jobOfferKey,
        client: wallet.publicKey,
        freelancer: freelancerKey,
        vault: vaultPda,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    return tx;
  }

  // ── cancel_job ────────────────────────────────────────────────────────────
  async function cancelJob(params: { jobOfferPda: string }): Promise<string> {
    if (!program || !wallet.publicKey) throw new Error("Wallet not connected");

    const jobOfferKey = new PublicKey(params.jobOfferPda);
    const vaultPda = deriveVaultPda(jobOfferKey);

    const tx = await program.methods
      .cancelJob()
      .accounts({
        jobOffer: jobOfferKey,
        client: wallet.publicKey,
        vault: vaultPda,
        systemProgram: SystemProgram.programId,
      })
      .rpc();

    return tx;
  }

  // ── decline_proposal ──────────────────────────────────────────────────────
  async function declineProposal(params: {
    jobOfferPda: string;
    freelancerPubkey: string;
  }): Promise<string> {
    if (!program || !wallet.publicKey) throw new Error("Wallet not connected");

    const jobOfferKey = new PublicKey(params.jobOfferPda);
    const freelancerKey = new PublicKey(params.freelancerPubkey);
    const proposalPda = deriveProposalPda(jobOfferKey, freelancerKey);

    const tx = await program.methods
      .declineProposal()
      .accounts({
        jobOffer: jobOfferKey,
        proposal: proposalPda,
        client: wallet.publicKey,
      })
      .rpc();

    return tx;
  }

  return {
    program,
    connected: !!wallet.publicKey,
    publicKey: wallet.publicKey,
    createOffer,
    offerProposal,
    acceptProposal,
    completeProposal,
    cancelJob,
    declineProposal,
  };
}
